### ISSUE TITLE
the foxbit endpoint is outdated

### ISSUE THREAD

**Issue by GabrielMochi** [MiguelMedeiros/foxbit-api#1]
The foxbit endpoint is outdated

Solution:

It is necessary to change the value of this variable:
`let wsAddress = "wss://apifoxbitprod.alphapoint.com/WSGateway/";`
to this value:
`let wsAddress = "wss://apifoxbitprodlb.alphapoint.com/WSGateway/";`

**Comment by Judahh** [comment]
New endpoint: "wss://api.foxbitapi.com.br/WSGateway/"
